# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _analyses
else:
    import _analyses

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _analyses.delete_SwigPyIterator

    def value(self) -> "PyObject *":
        return _analyses.SwigPyIterator_value(self)

    def incr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _analyses.SwigPyIterator_incr(self, n)

    def decr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _analyses.SwigPyIterator_decr(self, n)

    def distance(self, x: "SwigPyIterator") -> "ptrdiff_t":
        return _analyses.SwigPyIterator_distance(self, x)

    def equal(self, x: "SwigPyIterator") -> "bool":
        return _analyses.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _analyses.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _analyses.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _analyses.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _analyses.SwigPyIterator_previous(self)

    def advance(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _analyses.SwigPyIterator_advance(self, n)

    def __eq__(self, x: "SwigPyIterator") -> "bool":
        return _analyses.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: "SwigPyIterator") -> "bool":
        return _analyses.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _analyses.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _analyses.SwigPyIterator___isub__(self, n)

    def __add__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _analyses.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _analyses.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _analyses:
_analyses.SwigPyIterator_swigregister(SwigPyIterator)

import opensim.actuators
import opensim.simulation
import opensim.common
import opensim.simbody
class Kinematics(opensim.simulation.Analysis):
    r"""
    A class for recording the kinematics of the generalized coordinates
    of a model during a simulation.

    Author: Frank C. Anderson
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::Kinematics *":
        return _analyses.Kinematics_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.Kinematics_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.Kinematics_getClassName()

    def clone(self) -> "OpenSim::Kinematics *":
        return _analyses.Kinematics_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.Kinematics_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.Kinematics_swiginit(self, _analyses.new_Kinematics(*args))
    __swig_destroy__ = _analyses.delete_Kinematics

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.Kinematics_setStorageCapacityIncrements(self, aIncrement)

    def getAccelerationStorage(self) -> "OpenSim::Storage *":
        return _analyses.Kinematics_getAccelerationStorage(self)

    def getVelocityStorage(self) -> "OpenSim::Storage *":
        return _analyses.Kinematics_getVelocityStorage(self)

    def getPositionStorage(self) -> "OpenSim::Storage *":
        return _analyses.Kinematics_getPositionStorage(self)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.Kinematics_setModel(self, aModel)

    def setRecordAccelerations(self, aRecordAccelerations: "bool") -> "void":
        return _analyses.Kinematics_setRecordAccelerations(self, aRecordAccelerations)

    def begin(self, s: "State") -> "int":
        return _analyses.Kinematics_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.Kinematics_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.Kinematics_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.Kinematics_printResults(self, *args)

# Register Kinematics in _analyses:
_analyses.Kinematics_swigregister(Kinematics)

def Kinematics_safeDownCast(obj: "OpenSimObject") -> "OpenSim::Kinematics *":
    return _analyses.Kinematics_safeDownCast(obj)

def Kinematics_getClassName() -> "std::string const &":
    return _analyses.Kinematics_getClassName()

class Actuation(opensim.simulation.Analysis):
    r"""
    A class for recording the basic actuator information for a model
    during a simulation.

    Author: Frank C. Anderson
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::Actuation *":
        return _analyses.Actuation_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.Actuation_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.Actuation_getClassName()

    def clone(self) -> "OpenSim::Actuation *":
        return _analyses.Actuation_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.Actuation_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.Actuation_swiginit(self, _analyses.new_Actuation(*args))
    __swig_destroy__ = _analyses.delete_Actuation

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.Actuation_setStorageCapacityIncrements(self, aIncrement)

    def getForceStorage(self) -> "OpenSim::Storage *":
        return _analyses.Actuation_getForceStorage(self)

    def getSpeedStorage(self) -> "OpenSim::Storage *":
        return _analyses.Actuation_getSpeedStorage(self)

    def getPowerStorage(self) -> "OpenSim::Storage *":
        return _analyses.Actuation_getPowerStorage(self)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.Actuation_setModel(self, aModel)

    def begin(self, s: "State") -> "int":
        return _analyses.Actuation_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.Actuation_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.Actuation_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.Actuation_printResults(self, *args)

# Register Actuation in _analyses:
_analyses.Actuation_swigregister(Actuation)

def Actuation_safeDownCast(obj: "OpenSimObject") -> "OpenSim::Actuation *":
    return _analyses.Actuation_safeDownCast(obj)

def Actuation_getClassName() -> "std::string const &":
    return _analyses.Actuation_getClassName()

class MuscleAnalysis(opensim.simulation.Analysis):
    r"""
    A class for recording and computing basic quantities (length, shortening
    velocity, tendon length, ...) for muscles during a simulation.

    Author: Ajay Seth, Matthew Millard, Katherine Holzbaur, Frank C. Anderson
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::MuscleAnalysis *":
        return _analyses.MuscleAnalysis_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.MuscleAnalysis_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.MuscleAnalysis_getClassName()

    def clone(self) -> "OpenSim::MuscleAnalysis *":
        return _analyses.MuscleAnalysis_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.MuscleAnalysis_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.MuscleAnalysis_swiginit(self, _analyses.new_MuscleAnalysis(*args))
    __swig_destroy__ = _analyses.delete_MuscleAnalysis

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.MuscleAnalysis_setModel(self, aModel)

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.MuscleAnalysis_setStorageCapacityIncrements(self, aIncrement)

    def getPennationAngleStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getPennationAngleStorage(self)

    def getMuscleTendonLengthStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getMuscleTendonLengthStorage(self)

    def getFiberLengthStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getFiberLengthStorage(self)

    def getNormalizedFiberLengthStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getNormalizedFiberLengthStorage(self)

    def getTendonLengthStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getTendonLengthStorage(self)

    def getFiberVelocityStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getFiberVelocityStorage(self)

    def getNormalizedFiberVelocityStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getNormalizedFiberVelocityStorage(self)

    def getPennationAngularVelocityStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getPennationAngularVelocityStorage(self)

    def getForceStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getForceStorage(self)

    def getFiberForceStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getFiberForceStorage(self)

    def getActiveFiberForceStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getActiveFiberForceStorage(self)

    def getPassiveFiberForceStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getPassiveFiberForceStorage(self)

    def getActiveFiberForceAlongTendonStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getActiveFiberForceAlongTendonStorage(self)

    def getPassiveFiberForceAlongTendonStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getPassiveFiberForceAlongTendonStorage(self)

    def getFiberActivePowerStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getFiberActivePowerStorage(self)

    def getFiberPassivePowerStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getFiberPassivePowerStorage(self)

    def getTendonPowerStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getTendonPowerStorage(self)

    def getMusclePowerStorage(self) -> "OpenSim::Storage *":
        return _analyses.MuscleAnalysis_getMusclePowerStorage(self)

    def setMuscles(self, aMuscles: "ArrayStr") -> "void":
        return _analyses.MuscleAnalysis_setMuscles(self, aMuscles)

    def setCoordinates(self, aCoordinates: "ArrayStr") -> "void":
        return _analyses.MuscleAnalysis_setCoordinates(self, aCoordinates)

    def setComputeMoments(self, aTrueFalse: "bool") -> "void":
        return _analyses.MuscleAnalysis_setComputeMoments(self, aTrueFalse)

    def getComputeMoments(self) -> "bool":
        return _analyses.MuscleAnalysis_getComputeMoments(self)

    def begin(self, s: "State") -> "int":
        return _analyses.MuscleAnalysis_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.MuscleAnalysis_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.MuscleAnalysis_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.MuscleAnalysis_printResults(self, *args)

    def allocateStorageObjects(self) -> "void":
        r"""
        Intended for use only by GUI that holds one MuscleAnalysis and keeps changing attributes to generate various plots
        For all other use cases, the code handles the allocation/deallocation of resources internally.
        """
        return _analyses.MuscleAnalysis_allocateStorageObjects(self)

# Register MuscleAnalysis in _analyses:
_analyses.MuscleAnalysis_swigregister(MuscleAnalysis)

def MuscleAnalysis_safeDownCast(obj: "OpenSimObject") -> "OpenSim::MuscleAnalysis *":
    return _analyses.MuscleAnalysis_safeDownCast(obj)

def MuscleAnalysis_getClassName() -> "std::string const &":
    return _analyses.MuscleAnalysis_getClassName()

class InverseDynamics(opensim.simulation.Analysis):
    r"""
     Conditional comment: *
    A class for performing and recording Inverse Dynamics forces/moments
    on a motion trajectory.

    Author: Eran
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::InverseDynamics *":
        return _analyses.InverseDynamics_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.InverseDynamics_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.InverseDynamics_getClassName()

    def clone(self) -> "OpenSim::InverseDynamics *":
        return _analyses.InverseDynamics_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.InverseDynamics_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.InverseDynamics_swiginit(self, _analyses.new_InverseDynamics(*args))
    __swig_destroy__ = _analyses.delete_InverseDynamics

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.InverseDynamics_setStorageCapacityIncrements(self, aIncrement)

    def getStorage(self) -> "OpenSim::Storage *":
        return _analyses.InverseDynamics_getStorage(self)

    def getUseModelForceSet(self) -> "bool":
        return _analyses.InverseDynamics_getUseModelForceSet(self)

    def setUseModelForceSet(self, aUseModelForceSet: "bool") -> "void":
        return _analyses.InverseDynamics_setUseModelForceSet(self, aUseModelForceSet)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.InverseDynamics_setModel(self, aModel)

    def printResults(self, *args) -> "int":
        return _analyses.InverseDynamics_printResults(self, *args)

# Register InverseDynamics in _analyses:
_analyses.InverseDynamics_swigregister(InverseDynamics)

def InverseDynamics_safeDownCast(obj: "OpenSimObject") -> "OpenSim::InverseDynamics *":
    return _analyses.InverseDynamics_safeDownCast(obj)

def InverseDynamics_getClassName() -> "std::string const &":
    return _analyses.InverseDynamics_getClassName()

class StaticOptimization(opensim.simulation.Analysis):
    r"""
    This class implements static optimization to compute Muscle Forces and
    activations.

    Author: Jeff Reinbolt
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::StaticOptimization *":
        return _analyses.StaticOptimization_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.StaticOptimization_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.StaticOptimization_getClassName()

    def clone(self) -> "OpenSim::StaticOptimization *":
        return _analyses.StaticOptimization_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.StaticOptimization_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.StaticOptimization_swiginit(self, _analyses.new_StaticOptimization(*args))
    __swig_destroy__ = _analyses.delete_StaticOptimization

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.StaticOptimization_setStorageCapacityIncrements(self, aIncrement)

    def getActivationStorage(self) -> "OpenSim::Storage *":
        return _analyses.StaticOptimization_getActivationStorage(self)

    def getForceStorage(self) -> "OpenSim::Storage *":
        return _analyses.StaticOptimization_getForceStorage(self)

    def getUseModelForceSet(self) -> "bool":
        return _analyses.StaticOptimization_getUseModelForceSet(self)

    def setUseModelForceSet(self, aUseModelActuatorSet: "bool") -> "void":
        return _analyses.StaticOptimization_setUseModelForceSet(self, aUseModelActuatorSet)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.StaticOptimization_setModel(self, aModel)

    def setActivationExponent(self, aExponent: "double const") -> "void":
        return _analyses.StaticOptimization_setActivationExponent(self, aExponent)

    def getActivationExponent(self) -> "double":
        return _analyses.StaticOptimization_getActivationExponent(self)

    def setUseMusclePhysiology(self, useIt: "bool const") -> "void":
        return _analyses.StaticOptimization_setUseMusclePhysiology(self, useIt)

    def getUseMusclePhysiology(self) -> "bool":
        return _analyses.StaticOptimization_getUseMusclePhysiology(self)

    def setConvergenceCriterion(self, tolerance: "double const") -> "void":
        return _analyses.StaticOptimization_setConvergenceCriterion(self, tolerance)

    def getConvergenceCriterion(self) -> "double":
        return _analyses.StaticOptimization_getConvergenceCriterion(self)

    def setMaxIterations(self, maxIt: "int const") -> "void":
        return _analyses.StaticOptimization_setMaxIterations(self, maxIt)

    def getMaxIterations(self) -> "int":
        return _analyses.StaticOptimization_getMaxIterations(self)

    def begin(self, s: "State") -> "int":
        return _analyses.StaticOptimization_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.StaticOptimization_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.StaticOptimization_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.StaticOptimization_printResults(self, *args)

# Register StaticOptimization in _analyses:
_analyses.StaticOptimization_swigregister(StaticOptimization)

def StaticOptimization_safeDownCast(obj: "OpenSimObject") -> "OpenSim::StaticOptimization *":
    return _analyses.StaticOptimization_safeDownCast(obj)

def StaticOptimization_getClassName() -> "std::string const &":
    return _analyses.StaticOptimization_getClassName()

class ForceReporter(opensim.simulation.Analysis):
    r"""
    A class for recording the Forces applied to a model
    during a simulation.

    Author: Ayman Habib
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::ForceReporter *":
        return _analyses.ForceReporter_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.ForceReporter_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.ForceReporter_getClassName()

    def clone(self) -> "OpenSim::ForceReporter *":
        return _analyses.ForceReporter_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.ForceReporter_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.ForceReporter_swiginit(self, _analyses.new_ForceReporter(*args))
    __swig_destroy__ = _analyses.delete_ForceReporter

    def getForceStorage(self) -> "OpenSim::Storage const &":
        return _analyses.ForceReporter_getForceStorage(self)

    def updForceStorage(self) -> "OpenSim::Storage &":
        return _analyses.ForceReporter_updForceStorage(self)

    def getForcesTable(self) -> "OpenSim::TimeSeriesTable":
        r""" Get forces table."""
        return _analyses.ForceReporter_getForcesTable(self)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.ForceReporter_setModel(self, aModel)

    def includeConstraintForces(self, flag: "bool") -> "void":
        return _analyses.ForceReporter_includeConstraintForces(self, flag)

    def begin(self, s: "State") -> "int":
        return _analyses.ForceReporter_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.ForceReporter_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.ForceReporter_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.ForceReporter_printResults(self, *args)

# Register ForceReporter in _analyses:
_analyses.ForceReporter_swigregister(ForceReporter)

def ForceReporter_safeDownCast(obj: "OpenSimObject") -> "OpenSim::ForceReporter *":
    return _analyses.ForceReporter_safeDownCast(obj)

def ForceReporter_getClassName() -> "std::string const &":
    return _analyses.ForceReporter_getClassName()

class PointKinematics(opensim.simulation.Analysis):
    r"""
    A class for recording the kinematics of a point on a body
    of a model during a simulation.

    Author: Frank C. Anderson
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::PointKinematics *":
        return _analyses.PointKinematics_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.PointKinematics_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.PointKinematics_getClassName()

    def clone(self) -> "OpenSim::PointKinematics *":
        return _analyses.PointKinematics_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.PointKinematics_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.PointKinematics_swiginit(self, _analyses.new_PointKinematics(*args))
    __swig_destroy__ = _analyses.delete_PointKinematics

    def setBodyPoint(self, aBody: "std::string const &", aPoint: "Vec3") -> "void":
        return _analyses.PointKinematics_setBodyPoint(self, aBody, aPoint)

    def setBody(self, aBody: "PhysicalFrame") -> "void":
        return _analyses.PointKinematics_setBody(self, aBody)

    def setRelativeToBody(self, aBody: "PhysicalFrame") -> "void":
        return _analyses.PointKinematics_setRelativeToBody(self, aBody)

    def getBody(self) -> "OpenSim::PhysicalFrame const *":
        return _analyses.PointKinematics_getBody(self)

    def getRelativeToBody(self) -> "OpenSim::PhysicalFrame const *":
        return _analyses.PointKinematics_getRelativeToBody(self)

    def setPoint(self, aPoint: "Vec3") -> "void":
        return _analyses.PointKinematics_setPoint(self, aPoint)

    def getPoint(self, rPoint: "Vec3") -> "void":
        return _analyses.PointKinematics_getPoint(self, rPoint)

    def setPointName(self, aName: "std::string const &") -> "void":
        return _analyses.PointKinematics_setPointName(self, aName)

    def getPointName(self) -> "std::string const &":
        return _analyses.PointKinematics_getPointName(self)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.PointKinematics_setModel(self, aModel)

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.PointKinematics_setStorageCapacityIncrements(self, aIncrement)

    def getAccelerationStorage(self) -> "OpenSim::Storage *":
        return _analyses.PointKinematics_getAccelerationStorage(self)

    def getVelocityStorage(self) -> "OpenSim::Storage *":
        return _analyses.PointKinematics_getVelocityStorage(self)

    def getPositionStorage(self) -> "OpenSim::Storage *":
        return _analyses.PointKinematics_getPositionStorage(self)

    def begin(self, s: "State") -> "int":
        return _analyses.PointKinematics_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.PointKinematics_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.PointKinematics_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.PointKinematics_printResults(self, *args)

# Register PointKinematics in _analyses:
_analyses.PointKinematics_swigregister(PointKinematics)
cvar = _analyses.cvar
PointKinematicsNAME_LENGTH = cvar.PointKinematicsNAME_LENGTH
PointKinematicsBUFFER_LENGTH = cvar.PointKinematicsBUFFER_LENGTH

def PointKinematics_safeDownCast(obj: "OpenSimObject") -> "OpenSim::PointKinematics *":
    return _analyses.PointKinematics_safeDownCast(obj)

def PointKinematics_getClassName() -> "std::string const &":
    return _analyses.PointKinematics_getClassName()
PointKinematics.NAME_LENGTH = _analyses.cvar.PointKinematics_NAME_LENGTH
PointKinematics.BUFFER_LENGTH = _analyses.cvar.PointKinematics_BUFFER_LENGTH

class BodyKinematics(opensim.simulation.Analysis):
    r"""
    A class for recording the kinematics of the bodies
    of a model during a simulation.

    Author: Frank C. Anderson
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::BodyKinematics *":
        return _analyses.BodyKinematics_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.BodyKinematics_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.BodyKinematics_getClassName()

    def clone(self) -> "OpenSim::BodyKinematics *":
        return _analyses.BodyKinematics_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.BodyKinematics_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.BodyKinematics_swiginit(self, _analyses.new_BodyKinematics(*args))
    __swig_destroy__ = _analyses.delete_BodyKinematics

    def setStorageCapacityIncrements(self, aIncrement: "int") -> "void":
        return _analyses.BodyKinematics_setStorageCapacityIncrements(self, aIncrement)

    def getAccelerationStorage(self) -> "OpenSim::Storage *":
        return _analyses.BodyKinematics_getAccelerationStorage(self)

    def getVelocityStorage(self) -> "OpenSim::Storage *":
        return _analyses.BodyKinematics_getVelocityStorage(self)

    def getPositionStorage(self) -> "OpenSim::Storage *":
        return _analyses.BodyKinematics_getPositionStorage(self)

    def setExpressResultsInLocalFrame(self, aTrueFalse: "bool") -> "void":
        return _analyses.BodyKinematics_setExpressResultsInLocalFrame(self, aTrueFalse)

    def getExpressResultsInLocalFrame(self) -> "bool":
        return _analyses.BodyKinematics_getExpressResultsInLocalFrame(self)

    def setRecordCenterOfMass(self, aTrueFalse: "bool") -> "void":
        return _analyses.BodyKinematics_setRecordCenterOfMass(self, aTrueFalse)

    def setBodiesToRecord(self, listOfBodies: "ArrayStr") -> "void":
        return _analyses.BodyKinematics_setBodiesToRecord(self, listOfBodies)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.BodyKinematics_setModel(self, aModel)

    def begin(self, s: "State") -> "int":
        return _analyses.BodyKinematics_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.BodyKinematics_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.BodyKinematics_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.BodyKinematics_printResults(self, *args)

# Register BodyKinematics in _analyses:
_analyses.BodyKinematics_swigregister(BodyKinematics)

def BodyKinematics_safeDownCast(obj: "OpenSimObject") -> "OpenSim::BodyKinematics *":
    return _analyses.BodyKinematics_safeDownCast(obj)

def BodyKinematics_getClassName() -> "std::string const &":
    return _analyses.BodyKinematics_getClassName()

class JointReaction(opensim.simulation.Analysis):
    r"""
    An analysis for reporting the joint reaction loads from a model. For a given
    joint, the reaction load is calculated as the forces and moments required to
    constrain the body motions to satisfy the joint as if the joint did not
    exist.

    The reaction load acts at the joint center (mobilizer frame) of both the
    parent and child bodies and either force can be reported and expressed in
    any specified frame. The default behavior is the force on the child
    expressed in the ground frame.

    Author: Matt DeMers, Ajay Seth
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::JointReaction *":
        return _analyses.JointReaction_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.JointReaction_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.JointReaction_getClassName()

    def clone(self) -> "OpenSim::JointReaction *":
        return _analyses.JointReaction_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.JointReaction_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.JointReaction_swiginit(self, _analyses.new_JointReaction(*args))
    __swig_destroy__ = _analyses.delete_JointReaction

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.JointReaction_setModel(self, aModel)

    def getForcesFileName(self) -> "std::string const &":
        r""" Public accessors for the forcesFileName property"""
        return _analyses.JointReaction_getForcesFileName(self)

    def setForcesFileName(self, newForcesFile: "std::string const") -> "void":
        return _analyses.JointReaction_setForcesFileName(self, newForcesFile)

    def getJointNames(self) -> "OpenSim::Array< std::string > const &":
        r""" Public accessors for the JointNames property"""
        return _analyses.JointReaction_getJointNames(self)

    def setJointNames(self, jointNames: "ArrayStr") -> "void":
        return _analyses.JointReaction_setJointNames(self, jointNames)

    def getOnBody(self) -> "OpenSim::Array< std::string > const &":
        r""" Public accessors for the onBody property"""
        return _analyses.JointReaction_getOnBody(self)

    def setOnBody(self, onBody: "ArrayStr") -> "void":
        return _analyses.JointReaction_setOnBody(self, onBody)

    def getInFrame(self) -> "OpenSim::Array< std::string > const &":
        r""" Public accessors for the inFrame property"""
        return _analyses.JointReaction_getInFrame(self)

    def setInFrame(self, inFrame: "ArrayStr") -> "void":
        return _analyses.JointReaction_setInFrame(self, inFrame)

    def begin(self, s: "State") -> "int":
        return _analyses.JointReaction_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.JointReaction_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.JointReaction_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.JointReaction_printResults(self, *args)

# Register JointReaction in _analyses:
_analyses.JointReaction_swigregister(JointReaction)

def JointReaction_safeDownCast(obj: "OpenSimObject") -> "OpenSim::JointReaction *":
    return _analyses.JointReaction_safeDownCast(obj)

def JointReaction_getClassName() -> "std::string const &":
    return _analyses.JointReaction_getClassName()

class StatesReporter(opensim.simulation.Analysis):
    r"""
    A class for recording the states of a model
    during a simulation.

    Author: Ayman Habib
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::StatesReporter *":
        return _analyses.StatesReporter_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.StatesReporter_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.StatesReporter_getClassName()

    def clone(self) -> "OpenSim::StatesReporter *":
        return _analyses.StatesReporter_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.StatesReporter_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.StatesReporter_swiginit(self, _analyses.new_StatesReporter(*args))
    __swig_destroy__ = _analyses.delete_StatesReporter

    def getStatesStorage(self) -> "OpenSim::Storage const &":
        return _analyses.StatesReporter_getStatesStorage(self)

    def updStatesStorage(self) -> "OpenSim::Storage &":
        return _analyses.StatesReporter_updStatesStorage(self)

    def begin(self, s: "State") -> "int":
        return _analyses.StatesReporter_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.StatesReporter_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.StatesReporter_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.StatesReporter_printResults(self, *args)

# Register StatesReporter in _analyses:
_analyses.StatesReporter_swigregister(StatesReporter)

def StatesReporter_safeDownCast(obj: "OpenSimObject") -> "OpenSim::StatesReporter *":
    return _analyses.StatesReporter_safeDownCast(obj)

def StatesReporter_getClassName() -> "std::string const &":
    return _analyses.StatesReporter_getClassName()

class InducedAccelerations(opensim.simulation.Analysis):
    r"""
    A class to perform an Induced Accelerations analysis using a constraint-
    method of replacing external (contact) forces in order to determine
    the contributions of actuators to external reaction forces and thus
    model accelerations including that of the center-of-mass.
    The analysis reports the contributions of all forces to user identified
    accelerations of coordinates, bodies and/or center-of-mass.

    Induced Accelerations can apply any OpenSim::Constraint that implements
    setContactPointForInducedAccelerations() to replace external forces, which
    are precisely the same external forces (ExternalLoads file) applied
    during the forward dynamics simulation being analyzed.

    The ConstraintSet supplied must have the same number constraints as
    external forces AND apply to the same bodies with respect to ground.

    Author: Ajay Seth
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::InducedAccelerations *":
        return _analyses.InducedAccelerations_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.InducedAccelerations_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.InducedAccelerations_getClassName()

    def clone(self) -> "OpenSim::InducedAccelerations *":
        return _analyses.InducedAccelerations_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.InducedAccelerations_getConcreteClassName(self)

    def __init__(self, *args):
        r"""
        *Overload 1:*

        Construct an InducedAccelerations instance with a Model.

        :type aModel: :py:class:`Model`, optional
        :param aModel: Model for which the analysis is to be run.

        |

        *Overload 2:*

        Construct InducedAccelerations from file.

        :type aFileName: string
        :param aFileName: File name of the document.

        |

        *Overload 3:*

        Copy constructor.
        """
        _analyses.InducedAccelerations_swiginit(self, _analyses.new_InducedAccelerations(*args))
    __swig_destroy__ = _analyses.delete_InducedAccelerations

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.InducedAccelerations_setModel(self, aModel)

    def initialize(self, s: "State") -> "void":
        return _analyses.InducedAccelerations_initialize(self, s)

    def begin(self, s: "State") -> "int":
        return _analyses.InducedAccelerations_begin(self, s)

    def step(self, s: "State", stepNumber: "int") -> "int":
        return _analyses.InducedAccelerations_step(self, s, stepNumber)

    def end(self, s: "State") -> "int":
        return _analyses.InducedAccelerations_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.InducedAccelerations_printResults(self, *args)

    def addContactConstraintFromExternalForce(self, externalForce: "ExternalForce") -> "void":
        return _analyses.InducedAccelerations_addContactConstraintFromExternalForce(self, externalForce)

    def applyContactConstraintAccordingToExternalForces(self, s: "State") -> "OpenSim::Array< bool >":
        return _analyses.InducedAccelerations_applyContactConstraintAccordingToExternalForces(self, s)

# Register InducedAccelerations in _analyses:
_analyses.InducedAccelerations_swigregister(InducedAccelerations)

def InducedAccelerations_safeDownCast(obj: "OpenSimObject") -> "OpenSim::InducedAccelerations *":
    return _analyses.InducedAccelerations_safeDownCast(obj)

def InducedAccelerations_getClassName() -> "std::string const &":
    return _analyses.InducedAccelerations_getClassName()

class ProbeReporter(opensim.simulation.Analysis):
    r"""
    A class for reporting the outputs of all model-connected Probes to file during
    a simulation. This analysis will, at each 'step_interval', cycle through all
    model Probes and retrieve the SimTK::Vector of probe outputs via getProbeOutputs(s)
    and store them into a Storage object, which will get recorded to a file at the
    termination of the simulation. The column labels for each Probe output will
    come from the overridden method Array<string> getProbeOutputLabels() from the specific
    Probe subclass. A schematic of the ProbeReporter functionality is shown below
    (diagram below assumes a single probe, but ProbeReporter will cycle through every
    Probe in the Model):

                                    DEVELOPER NEEDS TO IMPLEMENT
                                    THIS INSIDE THE CHILD PROBE
                                    ============================
                                    |  SimTK::Vector           |
                              |---> |  computeProbeOutputs(s)  | ----|
                              |     ============================     |
      ===================     |                                      |     ==========================
      |  ProbeReporter  | -----                                      ----> |  Output to file        |
      |  Analysis       | -----                                      ----> |  at end of simulation  |
      ===================     |                                      |     ==========================
                              |     ============================     |
                              |---> |  Array<string>           | ----|
                                    |  getProbeOutputLabels()  |
                                    ============================
                                    DEVELOPER NEEDS TO IMPLEMENT
                                    THIS INSIDE THE CHILD PROBE



    Author: Tim Dorn
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::ProbeReporter *":
        return _analyses.ProbeReporter_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.ProbeReporter_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.ProbeReporter_getClassName()

    def clone(self) -> "OpenSim::ProbeReporter *":
        return _analyses.ProbeReporter_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.ProbeReporter_getConcreteClassName(self)

    def __init__(self, *args):
        _analyses.ProbeReporter_swiginit(self, _analyses.new_ProbeReporter(*args))
    __swig_destroy__ = _analyses.delete_ProbeReporter

    def getProbeStorage(self) -> "OpenSim::Storage const &":
        return _analyses.ProbeReporter_getProbeStorage(self)

    def updProbeStorage(self) -> "OpenSim::Storage &":
        return _analyses.ProbeReporter_updProbeStorage(self)

    def setModel(self, aModel: "Model") -> "void":
        return _analyses.ProbeReporter_setModel(self, aModel)

    def begin(self, s: "State") -> "int":
        return _analyses.ProbeReporter_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.ProbeReporter_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.ProbeReporter_end(self, s)

    def disableIntegrationOnlyProbes(self) -> "void":
        return _analyses.ProbeReporter_disableIntegrationOnlyProbes(self)

    def printResults(self, *args) -> "int":
        return _analyses.ProbeReporter_printResults(self, *args)

# Register ProbeReporter in _analyses:
_analyses.ProbeReporter_swigregister(ProbeReporter)

def ProbeReporter_safeDownCast(obj: "OpenSimObject") -> "OpenSim::ProbeReporter *":
    return _analyses.ProbeReporter_safeDownCast(obj)

def ProbeReporter_getClassName() -> "std::string const &":
    return _analyses.ProbeReporter_getClassName()

class OutputReporter(opensim.simulation.Analysis):
    r"""
    The OutputReporter Analysis is a wrapper for a TableReporter. It generates
    and writes TimeSeriesTables of Output values according to the names listed
    as properties of the Analysis. OutputReporter enables the AnalyzeTool to
    report on Outputs via the Analysis interface but backed by a TableReporter.
    The OutputReporter currently only supports Outputs of type: double, Vec3
    and SpatialVec. The OutputReporter will automatically write multiple files-
    a file for each supported Output type:
      - `<results-file-name>.sto` (as doubles),
      - `<results-file-name>Vec3.sto`, and
      - `<results-file-name>SpatialVec.sto`.

    Output paths can be absolute (e.g., `/joint/slider/tx|value`) or relative
    to the model (by leaving off the first slash; `joint/slider/tx|value`).
    For outputs on the model itself, you can use `|com_position`, etc. As
    explained for AbstractInput, the vertical bar denotes the output name.

    Note that the internal tables are reset at the beginning of a simulation or
    AnalyzeTool::run() and does not append results to previous tables.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::OutputReporter *":
        return _analyses.OutputReporter_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.OutputReporter_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.OutputReporter_getClassName()

    def clone(self) -> "OpenSim::OutputReporter *":
        return _analyses.OutputReporter_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.OutputReporter_getConcreteClassName(self)

    def copyProperty_output_paths(self, source: "OutputReporter") -> "void":
        return _analyses.OutputReporter_copyProperty_output_paths(self, source)

    def get_output_paths(self, i: "int") -> "std::string const &":
        return _analyses.OutputReporter_get_output_paths(self, i)

    def upd_output_paths(self, i: "int") -> "std::string &":
        return _analyses.OutputReporter_upd_output_paths(self, i)

    def set_output_paths(self, i: "int", value: "std::string const &") -> "void":
        return _analyses.OutputReporter_set_output_paths(self, i, value)

    def append_output_paths(self, value: "std::string const &") -> "int":
        return _analyses.OutputReporter_append_output_paths(self, value)

    def constructProperty_output_paths(self) -> "void":
        return _analyses.OutputReporter_constructProperty_output_paths(self)

    def __init__(self, *args):
        _analyses.OutputReporter_swiginit(self, _analyses.new_OutputReporter(*args))
    __swig_destroy__ = _analyses.delete_OutputReporter

# Register OutputReporter in _analyses:
_analyses.OutputReporter_swigregister(OutputReporter)

def OutputReporter_safeDownCast(obj: "OpenSimObject") -> "OpenSim::OutputReporter *":
    return _analyses.OutputReporter_safeDownCast(obj)

def OutputReporter_getClassName() -> "std::string const &":
    return _analyses.OutputReporter_getClassName()

class IMUDataReporter(opensim.simulation.Analysis):
    r"""
    A class for recording the readings off an IMU object placed on a model
    during a simulation.

    If using this reporter to compute IMU accelerometer signals based on kinematic
    information only (i.e., a solution from the InverseKinematicsTool), then
    set the property `compute_accelerations_without_forces` to true. This property
    will apply forces to the model corresponding to the kinematics that you
    provide as input so that the correct accelerations are computed. The input
    kinematics are splined and then prescribed to the model (via the
    PositionMotion class), and the applied forces are based on derivatives of
    these splines; therefore, you should ensure that the input kinematics produce
    the correct derivatives when splined. It is recommended that you don't not
    compute any quantities near the beginning or end of the time range in your
    data, since spline derivatives can be inaccurate in these regions.

    Author: Ayman Habib
    Version: 1.0
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def safeDownCast(obj: "OpenSimObject") -> "OpenSim::IMUDataReporter *":
        return _analyses.IMUDataReporter_safeDownCast(obj)

    def assign(self, aObject: "OpenSimObject") -> "void":
        return _analyses.IMUDataReporter_assign(self, aObject)

    @staticmethod
    def getClassName() -> "std::string const &":
        return _analyses.IMUDataReporter_getClassName()

    def clone(self) -> "OpenSim::IMUDataReporter *":
        return _analyses.IMUDataReporter_clone(self)

    def getConcreteClassName(self) -> "std::string const &":
        return _analyses.IMUDataReporter_getConcreteClassName(self)

    def copyProperty_report_orientations(self, source: "IMUDataReporter") -> "void":
        return _analyses.IMUDataReporter_copyProperty_report_orientations(self, source)

    def append_report_orientations(self, value: "bool const &") -> "int":
        return _analyses.IMUDataReporter_append_report_orientations(self, value)

    def constructProperty_report_orientations(self, initValue: "bool const &") -> "void":
        return _analyses.IMUDataReporter_constructProperty_report_orientations(self, initValue)

    def get_report_orientations(self, *args) -> "bool const &":
        return _analyses.IMUDataReporter_get_report_orientations(self, *args)

    def upd_report_orientations(self, *args) -> "bool &":
        return _analyses.IMUDataReporter_upd_report_orientations(self, *args)

    def set_report_orientations(self, *args) -> "void":
        return _analyses.IMUDataReporter_set_report_orientations(self, *args)

    def copyProperty_report_gyroscope_signals(self, source: "IMUDataReporter") -> "void":
        return _analyses.IMUDataReporter_copyProperty_report_gyroscope_signals(self, source)

    def append_report_gyroscope_signals(self, value: "bool const &") -> "int":
        return _analyses.IMUDataReporter_append_report_gyroscope_signals(self, value)

    def constructProperty_report_gyroscope_signals(self, initValue: "bool const &") -> "void":
        return _analyses.IMUDataReporter_constructProperty_report_gyroscope_signals(self, initValue)

    def get_report_gyroscope_signals(self, *args) -> "bool const &":
        return _analyses.IMUDataReporter_get_report_gyroscope_signals(self, *args)

    def upd_report_gyroscope_signals(self, *args) -> "bool &":
        return _analyses.IMUDataReporter_upd_report_gyroscope_signals(self, *args)

    def set_report_gyroscope_signals(self, *args) -> "void":
        return _analyses.IMUDataReporter_set_report_gyroscope_signals(self, *args)

    def copyProperty_report_accelerometer_signals(self, source: "IMUDataReporter") -> "void":
        return _analyses.IMUDataReporter_copyProperty_report_accelerometer_signals(self, source)

    def append_report_accelerometer_signals(self, value: "bool const &") -> "int":
        return _analyses.IMUDataReporter_append_report_accelerometer_signals(self, value)

    def constructProperty_report_accelerometer_signals(self, initValue: "bool const &") -> "void":
        return _analyses.IMUDataReporter_constructProperty_report_accelerometer_signals(self, initValue)

    def get_report_accelerometer_signals(self, *args) -> "bool const &":
        return _analyses.IMUDataReporter_get_report_accelerometer_signals(self, *args)

    def upd_report_accelerometer_signals(self, *args) -> "bool &":
        return _analyses.IMUDataReporter_upd_report_accelerometer_signals(self, *args)

    def set_report_accelerometer_signals(self, *args) -> "void":
        return _analyses.IMUDataReporter_set_report_accelerometer_signals(self, *args)

    def copyProperty_compute_accelerations_without_forces(self, source: "IMUDataReporter") -> "void":
        return _analyses.IMUDataReporter_copyProperty_compute_accelerations_without_forces(self, source)

    def append_compute_accelerations_without_forces(self, value: "bool const &") -> "int":
        return _analyses.IMUDataReporter_append_compute_accelerations_without_forces(self, value)

    def constructProperty_compute_accelerations_without_forces(self, initValue: "bool const &") -> "void":
        return _analyses.IMUDataReporter_constructProperty_compute_accelerations_without_forces(self, initValue)

    def get_compute_accelerations_without_forces(self, *args) -> "bool const &":
        return _analyses.IMUDataReporter_get_compute_accelerations_without_forces(self, *args)

    def upd_compute_accelerations_without_forces(self, *args) -> "bool &":
        return _analyses.IMUDataReporter_upd_compute_accelerations_without_forces(self, *args)

    def set_compute_accelerations_without_forces(self, *args) -> "void":
        return _analyses.IMUDataReporter_set_compute_accelerations_without_forces(self, *args)

    def copyProperty_frame_paths(self, source: "IMUDataReporter") -> "void":
        return _analyses.IMUDataReporter_copyProperty_frame_paths(self, source)

    def get_frame_paths(self, i: "int") -> "std::string const &":
        return _analyses.IMUDataReporter_get_frame_paths(self, i)

    def upd_frame_paths(self, i: "int") -> "std::string &":
        return _analyses.IMUDataReporter_upd_frame_paths(self, i)

    def set_frame_paths(self, i: "int", value: "std::string const &") -> "void":
        return _analyses.IMUDataReporter_set_frame_paths(self, i, value)

    def append_frame_paths(self, value: "std::string const &") -> "int":
        return _analyses.IMUDataReporter_append_frame_paths(self, value)

    def constructProperty_frame_paths(self) -> "void":
        return _analyses.IMUDataReporter_constructProperty_frame_paths(self)

    def __init__(self, *args):
        _analyses.IMUDataReporter_swiginit(self, _analyses.new_IMUDataReporter(*args))
    __swig_destroy__ = _analyses.delete_IMUDataReporter

    def setNull(self) -> "void":
        return _analyses.IMUDataReporter_setNull(self)

    def getOrientationsTable(self) -> "OpenSim::TimeSeriesTable_< SimTK::Quaternion_< double > > const &":
        return _analyses.IMUDataReporter_getOrientationsTable(self)

    def getGyroscopeSignalsTable(self) -> "OpenSim::TimeSeriesTable_< SimTK::Vec3 > const &":
        return _analyses.IMUDataReporter_getGyroscopeSignalsTable(self)

    def getAccelerometerSignalsTable(self) -> "OpenSim::TimeSeriesTable_< SimTK::Vec3 > const &":
        return _analyses.IMUDataReporter_getAccelerometerSignalsTable(self)

    def begin(self, s: "State") -> "int":
        return _analyses.IMUDataReporter_begin(self, s)

    def step(self, s: "State", setNumber: "int") -> "int":
        return _analyses.IMUDataReporter_step(self, s, setNumber)

    def end(self, s: "State") -> "int":
        return _analyses.IMUDataReporter_end(self, s)

    def printResults(self, *args) -> "int":
        return _analyses.IMUDataReporter_printResults(self, *args)

# Register IMUDataReporter in _analyses:
_analyses.IMUDataReporter_swigregister(IMUDataReporter)

def IMUDataReporter_safeDownCast(obj: "OpenSimObject") -> "OpenSim::IMUDataReporter *":
    return _analyses.IMUDataReporter_safeDownCast(obj)

def IMUDataReporter_getClassName() -> "std::string const &":
    return _analyses.IMUDataReporter_getClassName()



